services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8084


  api:
    image: comex/comex-api
    environment:
      DB_HOST: database
    ports:
      - "8080:8080"
volumes:
  db-volume: